### ISSUE TITLE
[Suggestion] Add yet another timestamp option

### ISSUE THREAD

**Issue by CatsArmy** [mattymatty97/LTC_AsyncLoggers#4] opened 2024-03-29 10:54 UTC
add a timestamp option that is just a timer 0 is when you launch the game and the rest is figured out by the system.

i just want to compare load times lol from with the new assetbundle cacher and without it

**Comment by mattymatty97** [comment] 2024-03-29 11:39
i do log both the first timestamp from my mod
`[19:36:20.6245319] [Warning:AsyncLoggers] AsyncLoggers Timestamps start at Thursday, 28 March 2024 19:36:19.5481202 UTC`

and in the sqlite file the actual real Application start timestamp
will be in the `Events` table as Application.Start

**Comment by mattymatty97** [comment] 2024-03-29 11:40
you can easily do the subtraction to get the time 😓

**Closed by mattymatty97** 2024-03-29 11:40 UTC

**Comment by CatsArmy** [comment] 2024-03-29 11:42
O damn ok it's just a config but ok damn we got computers to calculate things I'm not going to start doing math in my head just for that

**Comment by mattymatty97** [comment] 2024-03-29 13:20
there is the TickCouter option which uses the SystemTicks as measure ( and they start from 0 ) but are not precise

**Comment by mattymatty97** [comment] 2024-03-29 13:21
the issue is that doing DateTime calculations is slow and will affect the timings you get.. i can proabably create a SQL query to run on the sqlite file to auto-calculate the delta if you really need it

**Comment by CatsArmy** [comment] 2024-03-29 13:23
Isn't there a timer class in c# or am I confusing it with a different language
